spring:
  application:
    name: translator
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:10000/translator
    username: translator
    password: translator
server:
  tomcat:
    threads:
      max: 10

translator-api:
    url: "https://ftapi.pythonanywhere.com/"
